### ISSUE TITLE
linked github pages site 404'ed

### ISSUE THREAD

**Issue by Thomashighbaugh** [StrataWM/stratawm#1]
Clicking through the Github Pages link in the description renders a 404, which given how new this is I am sure you know but just in case here is an issue. 

Interesting project, looking forward to seeing where it goes.

**Comment by anantnrg** [comment]
Sorry for the late reply, didn't get the notification. It returns a 404 because I haven't created a site for it. I plan to, but I'm really bad at web design. Always frustrates me. I'm thinking of using Leptos. Will start working on it in a few days.

Cheers :)
